platform :ios, "7.0"

use_frameworks!

pod "AFNetworking"
pod "ReactiveCocoa"
pod "SDWebImage"
pod "SVProgressHUD"
pod "MJExtension"
pod "MJRefresh"
pod "Masonry"
pod "DACircularProgress"
pod "pop"
pod "NJKWebViewProgress"
pod "JSONModel"
